#!/usr/bin/env python3
"""
Generate 2D convolution kernel and test vectors (aligned with HLS C++).

Produces:
  hls/conv_kernel.h      - R, C, K defines + kernel_ref[] array
  input.txt              - quantized input image pixels
  expected_output.txt    - reference output (computed from quantized values)

NOTE: kernel.txt is no longer used. kernel_ref[] is embedded directly
in conv_kernel.h so that tb.cpp and scipy always use the exact same values.

Fixed-point format: ap_fixed<32,16>
  - 16 integer bits: covers [-32768, 32768) -- needed for convolution output
  - 16 fractional bits: precision = 1/65536 = 0.0000153
"""

from pathlib import Path
import numpy as np
from scipy import ndimage


# ---------- Parameters ----------
seed = np.random.randint(0, int(1e9))
print("Seed =", seed)
rng = np.random.default_rng(seed)

R = int(rng.integers(8, 16))   # rows (8..15)
C = int(rng.integers(8, 16))   # cols (8..15)
K = int(rng.choice([3, 5]))    # kernel size: 3 or 5

IMAGE_MIN  =   0.0
IMAGE_MAX  = 255.0
KERNEL_MIN =  -2.0
KERNEL_MAX =  +2.0

print(f"Image shape = ({R}, {C})")
print(f"Kernel shape = ({K}, {K})")


# ---------- Random input and kernel ----------
image  = rng.uniform(IMAGE_MIN,  IMAGE_MAX,  size=(R, C)).astype(np.float32)
kernel = rng.uniform(KERNEL_MIN, KERNEL_MAX, size=(K, K)).astype(np.float32)


# ---------- Simulate fixed-point quantization ----------
# ap_fixed<32,16>: 16 fractional bits -> precision = 1/65536
FRAC_BITS = 16
SCALE     = float(2 ** FRAC_BITS)

image_fxp  = (np.floor(image  * SCALE) / SCALE).astype(np.float32)
kernel_fxp = (np.floor(kernel * SCALE) / SCALE).astype(np.float32)


# ---------- Reference output using quantized values ----------
# Use float64 for scipy to avoid float32 rounding in accumulation
expected = ndimage.convolve(
    image_fxp.astype(np.float64),
    kernel_fxp.astype(np.float64),
    mode='constant', cval=0.0
).astype(np.float32)


# ---------- Write outputs ----------
# ---------- Write outputs ----------
here = Path(__file__).resolve().parent

# ---------- C header ----------
hdr = here / "conv_kernel.h"      # same folder as Makefile
with open(hdr, "w") as f:
    f.write("#ifndef CONV_KERNEL_H\n")
    f.write("#define CONV_KERNEL_H\n\n")
    f.write("// Auto-generated by generate_vectors.py -- do not edit\n")
    f.write("// conv2d_common.h must be included before this file\n\n")

    f.write(f"#define R {R}\n")
    f.write(f"#define C {C}\n")
    f.write(f"#define K {K}\n\n")

    # kernel_ref: quantized kernel values as static const float
    # tb.cpp reads this instead of kernel.txt -> always in sync with scipy
    f.write("// Kernel quantized to ap_fixed<32,16> precision\n")
    f.write("static const float kernel_ref[K][K] = {\n")
    for i in range(K):
        f.write("    {")
        for j in range(K):
            comma = "," if j < K - 1 else ""
            f.write(f" {kernel_fxp[i, j]:.10e}{comma}")
        f.write(" }")
        f.write(",\n" if i < K - 1 else "\n")
    f.write("};\n\n")
    f.write("#endif\n")


# ---------- input.txt (quantized pixel values) ----------
with open(here / "input.txt", "w") as f:
    f.write(f"{R} {C} {K}\n")
    for r in range(R):
        for c in range(C):
            f.write(f"{image_fxp[r, c]:.10e}\n")


# ---------- expected_output.txt ----------
with open(here / "expected_output.txt", "w") as f:
    for r in range(R):
        for c in range(C):
            f.write(f"{expected[r, c]:.10e}\n")


# ---------- Debug prints ----------
print(f"\nGenerated:")
print(f"  {hdr}  (has kernel_ref[])")
print(f"  {here / 'input.txt'}")
print(f"  {here / 'expected_output.txt'}")
print(f"\n  NOTE: kernel.txt no longer used -- kernel is in conv_kernel.h")

print(f"\nKernel (quantized, {K}x{K}):")
for row in kernel_fxp:
    print("  ", " ".join(f"{v: .6f}" for v in row))

print(f"\nInput image ({R}x{C}) -- first 4 rows:")
for row in image_fxp[:4]:
    print("  ", " ".join(f"{v: .3f}" for v in row))

print(f"\nExpected output -- first 4 rows:")
for row in expected[:4]:
    print("  ", " ".join(f"{v: .3f}" for v in row))

print(f"\nQuantization errors:")
print(f"  Max image error:  {np.max(np.abs(image - image_fxp)):.8f}")
print(f"  Max kernel error: {np.max(np.abs(kernel - kernel_fxp)):.8f}")
print(f"\nTolerance for tb.cpp: 0.5f")