#!/usr/bin/env python3
"""
Generate 2D convolution test vectors for HLS fixed-point project.

Produces:
  conv_kernel.h        - C header with R, C, K defines + kernel values
  input.txt                - input image pixels (quantized)
  expected_output.txt      - reference output (scipy convolve, quantized inputs)

NOTE: kernel values are embedded directly in conv_kernel.h so that
the C++ testbench and scipy always use the exact same kernel.
tb.cpp reads kernel from conv_kernel.h, NOT from a separate kernel.txt.

Fixed-point notes:
  data_t = ap_fixed<16,9>  covers [-256, 256), precision = 1/128 = 0.0078
  Image range:  [0, 255]
  Kernel range: [-2, 2]
  Tolerance for tb.cpp comparison: 0.5 (accounts for fixed-point error)
"""

from pathlib import Path
import numpy as np
from scipy import ndimage


# ----------------------------------------------------------------
#  Parameters
# ----------------------------------------------------------------
seed = np.random.randint(0, int(1e9))
print(f"Seed = {seed}")
rng = np.random.default_rng(seed)

R = int(rng.integers(8, 16))    # rows  (8..15)
C = int(rng.integers(8, 16))    # cols  (8..15)
K = int(rng.choice([3, 5]))     # kernel size: 3 or 5

IMAGE_MIN  =   0.0
IMAGE_MAX  = 255.0
KERNEL_MIN =  -2.0
KERNEL_MAX =  +2.0

print(f"Image shape : ({R}, {C})")
print(f"Kernel shape: ({K}, {K})")


# ----------------------------------------------------------------
#  Generate random input image and kernel
# ----------------------------------------------------------------
image  = rng.uniform(IMAGE_MIN,  IMAGE_MAX,  size=(R, C)).astype(np.float32)
kernel = rng.uniform(KERNEL_MIN, KERNEL_MAX, size=(K, K)).astype(np.float32)


# ----------------------------------------------------------------
#  Simulate fixed-point quantization
#  ap_fixed<16,9> has 7 fractional bits -> precision = 1/128 = 0.0078125
#  Use floor to match HLS ap_fixed truncation behaviour
# ----------------------------------------------------------------
FRAC_BITS = 7
SCALE     = float(2 ** FRAC_BITS)   # 128.0

image_fxp  = (np.floor(image  * SCALE) / SCALE).astype(np.float32)
kernel_fxp = (np.floor(kernel * SCALE) / SCALE).astype(np.float32)

print(f"\nMax quantization error (image):  "
      f"{np.max(np.abs(image - image_fxp)):.6f}")
print(f"Max quantization error (kernel): "
      f"{np.max(np.abs(kernel - kernel_fxp)):.6f}")


# ----------------------------------------------------------------
#  Compute reference output using QUANTIZED values
#  This matches what the fixed-point C++ will compute
# ----------------------------------------------------------------
expected = ndimage.convolve(
    image_fxp, kernel_fxp,
    mode='constant', cval=0.0
).astype(np.float32)


# ----------------------------------------------------------------
#  Output paths
# ----------------------------------------------------------------
here    = Path(__file__).resolve().parent


# ----------------------------------------------------------------
#  Write conv_kernel.h
#  Embeds R, C, K AND kernel_ref[] so tb.cpp and scipy are
#  always perfectly in sync — no separate kernel.txt needed.
# ----------------------------------------------------------------
hdr = here / "conv_kernel.h"
with open(hdr, "w") as f:
    f.write("#ifndef CONV_KERNEL_H\n")
    f.write("#define CONV_KERNEL_H\n\n")
    f.write("// Auto-generated by generate.py -- do not edit\n")
    f.write("// Include conv2d_common.h BEFORE this file (needs data_t)\n\n")

    f.write(f"#define R {R}\n")
    f.write(f"#define C {C}\n")
    f.write(f"#define K {K}\n\n")

    # Kernel values pre-quantized to ap_fixed<16,9> precision (7 frac bits)
    # Written as static const float so it compiles in both float and fixed modes
    f.write("// Kernel pre-quantized to ap_fixed<16,9> precision\n")
    f.write("// (7 fractional bits, step = 1/128 = 0.0078125)\n")
    f.write("static const float kernel_ref[K][K] = {\n")
    for i in range(K):
        f.write("    {")
        for j in range(K):
            comma = "," if j < K - 1 else ""
            f.write(f" {kernel_fxp[i, j]:.10e}{comma}")
        f.write(" }")
        f.write(",\n" if i < K - 1 else "\n")
    f.write("};\n\n")
    f.write("#endif // CONV_KERNEL_H\n")


# ----------------------------------------------------------------
#  Write input.txt  (quantized pixel values)
#  Format: first line = "R C K", then R*C float values one per line
# ----------------------------------------------------------------
with open(here / "input.txt", "w") as f:
    f.write(f"{R} {C} {K}\n")
    for r in range(R):
        for c in range(C):
            f.write(f"{image_fxp[r, c]:.10e}\n")


# ----------------------------------------------------------------
#  Write expected_output.txt  (reference from quantized inputs)
# ----------------------------------------------------------------
with open(here / "expected_output.txt", "w") as f:
    for r in range(R):
        for c in range(C):
            f.write(f"{expected[r, c]:.10e}\n")


# ----------------------------------------------------------------
#  Debug prints
# ----------------------------------------------------------------
print(f"\nGenerated files:")
print(f"  {hdr}")
print(f"  {here / 'input.txt'}")
print(f"  {here / 'expected_output.txt'}")
print(f"\n  NOTE: kernel.txt is no longer used.")
print(f"  tb.cpp reads kernel from conv_kernel.h (kernel_ref array)")

print(f"\nKernel ({K}x{K}) — quantized, written to conv_kernel.h:")
for row in kernel_fxp:
    print("  ", " ".join(f"{v: .6f}" for v in row))

print(f"\nInput image ({R}x{C}) — first 4 rows (quantized):")
for row in image_fxp[:4]:
    print("  ", " ".join(f"{v: .2f}" for v in row))

print(f"\nExpected output — first 4 rows:")
for row in expected[:4]:
    print("  ", " ".join(f"{v: .4f}" for v in row))

print(f"\n--- Tolerance guide ---")
print(f"Fixed-point step size : 1/{int(SCALE)} = {1.0/SCALE:.7f}")
print(f"Worst case accum error: {K}x{K}={K*K} MACs * step^2 = "
      f"{K*K * (1.0/SCALE)**2:.6f}")
print(f"Recommended TOLERANCE in tb.cpp: 0.5f")
